package qupath.lib.deep_learning;

import java.util.Collection;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import qupath.lib.objects.PathObject;

/**
 * 
 * Class for the storing of high-level features generated by deep learning feature extraction 
 * and connecting them to the corresponding PathObject. 
 * These features are too many and too abstract to just add to the measurement list of a PathObject.
 * 
 * @author Sam Vanmassenhove
 *
 */
public class PathFeatureObject extends AbstractFeatureObject {
	
	private static final Logger logger = LoggerFactory.getLogger(PathFeatureObject.class);
	
	private PathObject pathObject;
	private Collection <Double> featureList; // List of high-level features: should all be doubles
	
	public PathFeatureObject (final PathObject pathObject, final Collection <Double> featureList) {
		super(pathObject, featureList);
	}
	
	public PathFeatureObject (final PathObject pathObject, final double [] features) {
		super(pathObject, features);
	}

}
